# Generated by Django 3.0.8 on 2020-07-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahradeen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='portfolio_img'),
        ),
    ]
