# Generated by Django 3.0.8 on 2020-07-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahradeen', '0002_auto_20200708_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='long_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
