# Generated by Django 3.0.8 on 2020-07-08 08:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import zahradeen.models


class Migration(migrations.Migration):

    dependencies = [
        ('zahradeen', '0003_auto_20200708_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='page_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=zahradeen.models.image_upload_to)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zahradeen.Portfolio')),
            ],
        ),
    ]
